# Generated by Django 2.1.1 on 2018-10-04 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('hwID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('hwName', models.CharField(max_length=60)),
                ('hwContent', models.CharField(max_length=360)),
                ('hwStart', models.CharField(max_length=25)),
                ('hwEnd', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hwID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Homework')),
            ],
        ),
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticeTitle', models.CharField(max_length=40)),
                ('noticeContent', models.CharField(max_length=360)),
            ],
        ),
        migrations.CreateModel(
            name='StuAccount',
            fields=[
                ('stuID', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('stuName', models.CharField(max_length=10)),
                ('stuPassword', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='homeworkupload',
            name='stuID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.StuAccount'),
        ),
        migrations.AddField(
            model_name='admin',
            name='stuID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.StuAccount'),
        ),
    ]
