# Generated by Django 2.1.1 on 2018-10-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkupload',
            name='hwID',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='homeworkupload',
            name='stuID',
            field=models.CharField(max_length=13),
        ),
    ]
