# Generated by Django 2.1.1 on 2018-10-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_stucheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='id',
        ),
        migrations.AlterField(
            model_name='admin',
            name='stuID',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
    ]
