# Generated by Django 2.1.2 on 2018-10-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20181006_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuID', models.CharField(max_length=13)),
                ('nickname', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=360)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
