# Generated by Django 2.1.2 on 2018-10-07 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_statistics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='statistics',
        ),
    ]
