# Generated by Django 2.1.2 on 2018-10-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_auto_20181008_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
