# Generated by Django 2.1.2 on 2018-11-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_auto_20181008_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='talk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=200)),
                ('talk_date', models.DateField(auto_now=True)),
                ('talk_time', models.CharField(max_length=10)),
            ],
        ),
    ]
